variables:
	{gateregion} = 1
	{sigencount} = 7
	{sigen1cflag} = false
	{sigen1rflag} = false
	{sigen2cflag} = false
	{sigen2rflag} = false
	{sigen3cflag} = false
	{sigen3rflag} = false
	{true} = true
	
on Skript start:
	while {true} is true:
		set {_date} to 7
		while {_date} isn't 0:
			set {_now} to "%now%"
			set {_date.time::*} to {_now} split at " "

			set {_date::*} to {_date.time::1} split at "/"
			set {_time::*} to {_date.time::2} split at ":"

			set {_time.hour} to {_time::1}
			set {_time.minute} to {_time::2}
			
			set {_hours} to {_time.hour} parsed as number
			set {_minutes} to {_time.minute} parsed as number
			broadcast "%{_hours}% %{_minutes}%"
			if {_hours} <= 17:
				set {_waithours} to 17 -{_hours}
			else:
				set {_waithours} to 43 -{_hours}
			set {_waitminutes} to 59 -{_minutes}
			set {_wait} to "%{_waithours}% hours and %{_waitminutes}% minutes" parsed as timespan
			broadcast "%{_wait}%"
			wait {_wait}
			set {_now} to "%now%"
			set {_date.time::*} to {_now} split at " "

			set {_date::*} to {_date.time::1} split at "/"
			set {_time::*} to {_date.time::2} split at ":"

			set {_date.day} to {_date::3}
			set {_date.month} to {_date::2}
			set {_date.year} to {_date::1}

			set {_year} to {_date.year} parsed as number
			set {_yearmoduled} to {_year}
			set {_num} to 4
			set {_count} to 0
			while {_yearmoduled} is greater than or equal to {_num}:
				set {_count} to {_count} + 1
				set {_yearmoduled} to {_yearmoduled} - {_num}
			add -35 to {_year}
			add {_count} to {_year}
			set {_month} to {_date.month} parsed as number
			if {_month} is 1:
				set {_month} to 36
				add -1 to {_year}
			else if {_month} is 2:
				set {_month} to 39
				add -1 to {_year}
			else if {_month} is 3:
				set {_month} to 10
			else if {_month} is 4:
				set {_month} to 13
			else if {_month} is 5:
				set {_month} to 15
			else if {_month} is 6:
				set {_month} to 18
			else if {_month} is 7:
				set {_month} to 20
			else if {_month} is 8:
				set {_month} to 23
			else if {_month} is 9:
				set {_month} to 26
			else if {_month} is 10:
				set {_month} to 28
			else if {_month} is 11:
				set {_month} to 31
			else:
				set {_month} to 39
			set {_day} to {_date.day} parsed as number
			add {_year} to {_sum}
			add {_month} to {_sum}
			add {_day} to {_sum}
			set {_summoduled} to {_sum}
			set {_num} to 7
			set {_count} to 0
			while {_summoduled} is greater than or equal to {_num}:
				set {_count} to {_count} + 1
				set {_summoduled} to {_summoduled} - {_num}
			set {_date} to {_summoduled}
		broadcast "60•bŒã‚É‘Œ¹%{gateregion}%‚ÌÄ¶¬‚ğs‚¢‚Ü‚·B"
		wait 30 seconds
		broadcast "30•bŒã‚É‘Œ¹%{gateregion}%‚ÌÄ¶¬‚ğs‚¢‚Ü‚·B"
		wait 20 seconds
		broadcast "10•bŒã‚É‘Œ¹%{gateregion}%‚ÌÄ¶¬‚ğs‚¢‚Ü‚·B"
		wait 1 seconds
		broadcast "9•bŒã‚É‘Œ¹%{gateregion}%‚ÌÄ¶¬‚ğs‚¢‚Ü‚·B"
		wait 1 seconds
		broadcast "8•bŒã‚É‘Œ¹%{gateregion}%‚ÌÄ¶¬‚ğs‚¢‚Ü‚·B"
		wait 1 seconds
		broadcast "7•bŒã‚É‘Œ¹%{gateregion}%‚ÌÄ¶¬‚ğs‚¢‚Ü‚·B"
		wait 1 seconds
		broadcast "6•bŒã‚É‘Œ¹%{gateregion}%‚ÌÄ¶¬‚ğs‚¢‚Ü‚·B"
		wait 1 seconds
		broadcast "5•bŒã‚É‘Œ¹%{gateregion}%‚ÌÄ¶¬‚ğs‚¢‚Ü‚·B"
		wait 1 seconds
		broadcast "4•bŒã‚É‘Œ¹%{gateregion}%‚ÌÄ¶¬‚ğs‚¢‚Ü‚·B"
		wait 1 seconds
		broadcast "3•bŒã‚É‘Œ¹%{gateregion}%‚ÌÄ¶¬‚ğs‚¢‚Ü‚·B"
		wait 1 seconds
		broadcast "2•bŒã‚É‘Œ¹%{gateregion}%‚ÌÄ¶¬‚ğs‚¢‚Ü‚·B"
		wait 1 seconds
		broadcast "1•bŒã‚É‘Œ¹%{gateregion}%‚ÌÄ¶¬‚ğs‚¢‚Ü‚·B"
		if {gateregion} = 1:
			set {sigen1rflag} to true
		else if {gateregion} = 2:
			set {sigen2rflag} to true
		else:
			set {sigen3rflag} to true
		set {deletesigen} to {sigencount} -3
		execute console command "/rg remove sigenspawn%{gateregion}% -w sigen%{deletesigen}%"
		execute console command "/rg remove sigen%{gateregion}%out -w sigen%{deletesigen}%"
		execute console command "/wb sigen%{deletesigen}% clear"
		execute console command "/mv unload sigen%{deletesigen}%"
		wait 3 seconds
		zip directory "sigen%{deletesigen}%" to zip "sigen%{deletesigen}%.zip"
		move file "sigen%{deletesigen}%.zip" to "sigenbackup"
		execute console command "/mv load sigen%{deletesigen}%"
		execute console command "/mv delete sigen%{deletesigen}%"
		execute console command "/mv confirm"
		execute console command "/mv create sigen%{sigencount}% normal"
		wait 5 seconds
		copy file "regions\%{gateregion}%\regions.yml" to "plugins\WorldGuard\worlds\sigen%{sigencount}%"
		if {gateregion} is 3:
			set {gateregion} to 1
		execute console command "/rg reload"
		execute console command "/wb sigen%{sigencount}% set 50 spawn"
		execute console command "/wb sigen%{sigencount}% fill 500 10 false"
		execute console command "/wb fill confirm"
		wait 3 seconds
		execute console command "/wb sigen%{sigencount}% set 2000 spawn"
		if {gateregion} is 1:
			set {sigen1rflag} to false
		else if {gateregion} is 2:
			set {sigen2rflag} to false
		else:
			set {sigen3rflag} to false
		if {gateregion} is 1:
			set {sigen1cflag} to true
		else if {gateregion} is 2:
			set {sigen2cflag} to true
		else:
			set {sigen3cflag} to true
		add 1 to {sigencount}
		add 1 to {gateregion}

on region enter:
	wait 1 tick
	if "%region at player%" contains "sigengate1":
		if {gateowner} is the owner of the region:
			if {sigen1rflag} is true:
				send "&4Œ»İÄ¶¬’†‚Å‚·"
			else if {sigen1cflag} is true:
				message "teleported"
				set {sigen1cflag} to false
				execute console command "/mvtp %player% sigen%{sigencount} - 3%"
				wait 10 tick
				set {sigengate1} to player's location
				set y coordinate of {sigengate1} to 65
				set x coordinate of {sigengate1} to 0
				set z coordinate of {sigengate1} to 0
				teleport the player to {sigengate1}
				paste schematic "sigenspawn" at location of player
				set z coordinate of {sigengate1} to -3
			else:
				message "teleported"
				teleport the player to {sigengate1}
on region enter:
	wait 1 tick
	if "%region at player%" contains "sigengate2":
		if {gateowner} is the owner of the region:
			if {sigen2rflag} is true:
				send "&4Œ»İÄ¶¬’†‚Å‚·"
			else if {sigen2cflag} is true:
				message "teleported"
				set {sigen1cflag} to false
				execute console command "/mvtp %player% sigen%{sigencount} - 2%"
				wait 10 tick
				set {sigengate2} to player's location
				set y coordinate of {sigengate2} to 65
				set x coordinate of {sigengate2} to 0
				set z coordinate of {sigengate2} to 0
				teleport the player to {sigengate2}
				paste schematic "sigenspawn" at location of player
				set z coordinate of {sigengate2} to -3
			else:
				message "teleported"
				teleport the player to {sigengate2}
on region enter:
	wait 1 tick
	if "%region at player%" contains "sigengate3":
		if {gateowner} is the owner of the region:
			if {sigen1rflag} is true:
				send "&4Œ»İÄ¶¬’†‚Å‚·"
			else if {sigen1cflag} is true:
				message "teleported"
				set {sigen1cflag} to false
				execute console command "/mvtp %player% sigen%{sigencount} - 1%"
				wait 10 tick
				set {sigengate1} to player's location
				set y coordinate of {sigengate3} to 65
				set x coordinate of {sigengate3} to 0
				set z coordinate of {sigengate3} to 0
				teleport the player to {sigengate3}
				paste schematic "sigenspawn" at location of player
				set z coordinate of {sigengate3} to -3
			else:
				message "teleported"
				teleport the player to {sigengate3}
on region enter:
	wait 1 tick
	if "%region at player%" contains "sigen1out":
		if {gateowner} is the owner of the region:
			message "teleported"
			teleport the player to {resoursespawn}
on region enter:
	wait 1 tick
	if "%region at player%" contains "sigen2out":
		if {gateowner} is the owner of the region:
			message "teleported"
			teleport the player to {resoursespawn}
on region enter:
	wait 1 tick
	if "%region at player%" contains "sigen3out":
		if {gateowner} is the owner of the region:
			message "teleported"
			teleport the player to {resoursespawn}

command /setresourcesspawn:
	permission: regenresourse.setspawn
	description: Set resourse spawn
	trigger:
		set {resoursespawn} to player's location
command /setgateowner:
	permission: regenresourse.setowner
	description: Set owner spawn
	trigger:
		set {gateowner} to the player
		message "Set owner %{gateowner}%"